server:
  port: 8080
spring:
  application:
    name: "TestReactive"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: "local"
aws:
  dynamodb:
    endpoint: "http://localhost:4566"
  region: "us-east-1"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/userQueue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
